name: ov_watch_app
description: Android companion app for OV-Watch.
publish_to: none
version: 0.1.2+3

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^1.2.0
  flutter_classic_bluetooth: ^1.6.0
  sqflite: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: launcher_icon
  image_path: assets/branding/ov_health_icon.png
  adaptive_icon_background: "#EFF5FF"
  adaptive_icon_foreground: assets/branding/ov_health_icon.png
  adaptive_icon_foreground_inset: 18
  min_sdk_android: 24
